/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2017-11-08 09:59:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class parts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header>\r\n");
      out.write("      <div id=\"ng-layout-topbar\" class=\"\">\r\n");
      out.write("        <a class=\"menu-button\" href=\"#\">\r\n");
      out.write("          <i class=\"fa fa-bars\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a class=\"logo\">\r\n");
      out.write("          <img alt=\"logo\" src=\"assets/img/mobile-daimler-logo.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"ui-g\" style=\"float: right;\">\r\n");
      out.write("          <ul class=\"ng-topbar-menu\">\r\n");
      out.write("            <li style=\"color:white;width:20px;\">\r\n");
      out.write("              <i class=\"fa fa-user\"></i>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li style=\"color:white;margin-top:25%;\">\r\n");
      out.write("              Hi ");
      out.print((String)request.getAttribute("userName"));
      out.write(" | HO\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <aside class=\"\">\r\n");
      out.write("      <div  class=\"ng-tns-c1-0\" id=\"ng-layout-sidebar\">\r\n");
      out.write("        <div  class=\"ng-layout-menu\">\r\n");
      out.write("          <a  class=\"ng-tns-c1-0 active-menuitem\" id=\"dashboard_menutitle\" href=\"#/dashboard\">\r\n");
      out.write("            <i  class=\"fa fa-dashboard\" title=\"Dashboard\"></i>\r\n");
      out.write("            <span  class=\"ng-tns-c1-0\">Dashboard</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <a id=\"asbd_menutitle\" class=\"ng-tns-c1-0\">\r\n");
      out.write("            <i class=\"fa fa-line-chart\"></i>\r\n");
      out.write("            <span class=\"ng-tns-c1-0\">ASBD</span>\r\n");
      out.write("            <i class=\"fa fa-angle-down ng-tns-c1-0 slide-arrow\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"ng-tns-c1-0 submenushow\">\r\n");
      out.write("            <a id=\"parts_submenutitle\" class=\"ng-tns-c1-0\" onclick=\"openCity(event, 'part')\">\r\n");
      out.write("              <i class=\"fa fa-gears\" title=\"Parts\"></i>\r\n");
      out.write("              <span class=\"ng-tns-c1-0\">Parts</span>\r\n");
      out.write("            </a>\r\n");
      out.write("           <!--  <a id=\"contracts_submenutitle\" class=\"ng-tns-c1-0\" href=\"#/contracts\">\r\n");
      out.write("              <i class=\"fa fa-file-text\" title=\"Service Contracts\"></i>\r\n");
      out.write("              <span class=\"ng-tns-c1-0\">Service Contracts</span>\r\n");
      out.write("            </a> -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <a id=\"ccare_menutitle\" class=\"ng-tns-c1-0\" href=\"#/customer-care\">\r\n");
      out.write("            <i class=\"fa fa-handshake-o\" title=\"Customer Care\"></i>\r\n");
      out.write("            <span class=\"ng-tns-c1-0\">Customer Care</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"ng-tns-c1-0\">\r\n");
      out.write("            <i class=\"fa fa-arrow-circle-o-left ng-tns-c1-0\"></i>\r\n");
      out.write("\r\n");
      out.write("            <span class=\"ng-tns-c1-0\">Toggle Navigation</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"ng-tns-c1-0\" id=\"logout_menutitle\" href=\"#/logout\">\r\n");
      out.write("            <i class=\"fa fa-power-off\" title=\"Logout\"></i>\r\n");
      out.write("            <span class=\"ng-tns-c1-0\">Logout</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"ng-layout-content\" class=\"layout\">\r\n");
      out.write("      <div class=\"ui-breadcrumb ui-widget ui-widget-header ui-helper-clearfix ui-corner-all\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"ui-breadcrumb-home fa fa-home\"></li>\r\n");
      out.write("          <li class=\"ui-breadcrumb-chevron fa fa-chevron-right\"></li>\r\n");
      out.write("          <li role=\"menuitem\" class=\"\">\r\n");
      out.write("            <a class=\"ui-menuitem-link\" href=\"#\">\r\n");
      out.write("              <span class=\"ui-menuitem-text\">Dashboard</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"ui-breadcrumb-chevron fa fa-chevron-right\"></li>\r\n");
      out.write("          <li role=\"menuitem\" class=\"\">\r\n");
      out.write("            <a class=\"ui-menuitem-link\" href=\"#\">\r\n");
      out.write("              <span class=\"ui-menuitem-text\">After Sales</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"part\" class=\"tabcontent\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"parts\" style=\"width: 800px; height: 600px;\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"warrantyRepair\" class=\"tabcontent\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"warranty\" style=\"width: 800px; height: 700px;\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" \tsrc=\"https://public.tableau.com/javascripts/api/tableau-2.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("     $.ajax({\r\n");
      out.write("\r\n");
      out.write("\t\t\turl : 'http://localhost:9191/doLogin',\r\n");
      out.write("\t\t\t//url : 'http://192.168.1.135:8080/Noodle/Noodle?page=',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tticket = data;\r\n");
      out.write("\t\t\t\tconsole.log('ajax success = ' + ticket);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(data) {\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t// var errorMsg = 'Ajax request failed: ' + xhr.responseText;\r\n");
      out.write("\t\t\t\tconsole.log('ajax error = ' + JSON.stringify(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function openCity(evt, cityName) {\r\n");
      out.write("\tvar i, tabcontent, tablinks;\r\n");
      out.write("\ttabcontent = document.getElementsByClassName(\"tabcontent\");\r\n");
      out.write("\tfor (i = 0; i < tabcontent.length; i++) {\r\n");
      out.write("\t\ttabcontent[i].style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\ttablinks = document.getElementsByClassName(\"tablinks\");\r\n");
      out.write("\tfor (i = 0; i < tablinks.length; i++) {\r\n");
      out.write("\t\ttablinks[i].className = tablinks[i].className.replace(\r\n");
      out.write("\t\t\t\t\" active\", \"\");\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(cityName).style.display = \"block\";\r\n");
      out.write("\tevt.currentTarget.className += \" active\";\r\n");
      out.write("\tif (cityName == \"part\") {\r\n");
      out.write("\t\tinitParts();\r\n");
      out.write("\t} else if (cityName == \"warrantyRepair\") {\r\n");
      out.write("\t\tinitViz1();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function initParts() {\r\n");
      out.write("\t//alert(\"ticket\" + ticket);\r\n");
      out.write("\t// this has to come from ajax response  http://192.168.1.31/#/workbooks/8/views\r\n");
      out.write("\t// http://192.168.1.31/trusted/Zk0HeIHKSa-Tbzgl7jlgLQ==:9fltIFoH3ojTf-BekNfm3k9d/views/Vizualizations/Region\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t// http://localhost:9191/trusted/Gz7lB42-RY28TDucm-PumQ==:XTDRmECCfy52fW-pU54aDC5N/views/Superstore/Customers\r\n");
      out.write("\t\r\n");
      out.write("\tvar containerDiv = document.getElementById(\"parts\"), url = \"http://www.google.com/\"+ \"trusted/\" + ticket+\"/views/Superstore/Customers\", options = {\r\n");
      out.write("\t\thideTabs : false\r\n");
      out.write("\t}; \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* var containerDiv = document.getElementById(\"parts\"), url = \"http://192.168.1.31/trusted/\"+ticket+\"/views/Visualizations/Region\", options = {\r\n");
      out.write("\t\thideTabs : false\r\n");
      out.write("\t}; */\r\n");
      out.write("\tvar viz = new tableau.Viz(containerDiv, url, options);\r\n");
      out.write("\t// Create a viz object and embed it in the container div.\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
